[package]
name = "ssh_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
russh = "0.51"
russh-keys = "0.49.2"
russh-sftp = "2.1.0"
env_logger = "0.11"
log = "0.4"
